#!/bin/bash
#

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root"
   exit
fi

echo >>/etc/udev/rules.d/99-dfu.rules
echo \# Intel EDU in DFU Mode >>/etc/udev/rules.d/99-dfu.rules
echo SUBSYSTEM==\"tty\", ENV{ID_REVISION}==\"8087\", ENV{ID_MODEL_ID}==\"0a9f\", MODE=\"0666\", ENV{ID_MM_DEVICE_IGNORE}=\"1\" >>/etc/udev/rules.d/99-dfu.rules
echo SUBSYSTEM==\"usb\", ATTR{idVendor}==\"8087\", ATTR{idProduct}==\"0a99\", MODE=\"666\", ENV{ID_MM_DEVICE_IGNORE}=\"1\" >>/etc/udev/rules.d/99-dfu.rules


/etc/init.d/udev restart

